# WHAT: West manifest for ZMK dependencies.
# WHY: Specifies the exact revision of the ZMK core repo to maintain compatibility with nice_nano_v2.
# HOW: Configures zmk remote with defaults revision v0.3.
manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: config
